import { Dimensions, Platform } from 'react-native';
import { createThemedStyleSheet } from './theme/createThemedStyleSheet';

const SCREEN_WIDTH = Dimensions.get('window').width;

const createStyles = (isDark = false) =>
  createThemedStyleSheet(
    {
      safeArea: {
        flex: 1,
        backgroundColor: '#F6F7F4',
        position: 'relative',
      },
      mobileMenuWrapper: {
        position: 'absolute',
        top: 16,
        right: 16,
        zIndex: 40,
      },
      container: {
        flex: 1,
        height: '100%',
        backgroundColor: '#F6F7F4',
        paddingTop: 20,
      },
      authContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 24,
        gap: 24,
      },
      authTitle: {
        fontSize: 28,
        fontWeight: '700',
        color: '#17202A',
        textAlign: 'center',
      },
      authSubtitle: {
        fontSize: 16,
        color: '#5F6B7A',
        textAlign: 'center',
        lineHeight: 22,
      },
      authButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        paddingHorizontal: 24,
        paddingVertical: 14,
        borderRadius: 28,
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#D8E1E1',
        shadowColor: '#000000',
        shadowOpacity: 0.06,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        elevation: 3,
      },
      authButtonIcon: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#F6F7F4',
        alignItems: 'center',
        justifyContent: 'center',
      },
      authButtonIconLabel: {
        fontSize: 18,
        fontWeight: '700',
        color: '#FFFFFF',
      },
      authButtonDisabled: {
        opacity: 0.7,
      },
      authButtonLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#17202A',
      },
      sessionHeader: {
        paddingHorizontal: 24,
        paddingTop: 12,
        marginBottom: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
      },
      sessionTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#17202A',
      },
      menuButtonWrapper: {
        borderRadius: 20,
        overflow: 'hidden',
      },
      menuButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
      },
      sessionAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#FCE7E8',
        alignItems: 'center',
        justifyContent: 'center',
      },
      sessionAvatarImage: {
        width: 40,
        height: 40,
        borderRadius: 20,
      },
      sessionAvatarText: {
        fontSize: 16,
        fontWeight: '700',
        color: '#17202A',
      },
      title: {
        fontSize: 28,
        fontWeight: '700',
        color: '#17202A',
        textAlign: 'center',
        marginBottom: 16,
      },
      carousel: {
        flex: 1,
        height: '100%',
      },
      carouselContent: {
        alignItems: 'stretch',
        height: '100%',
      },
      carouselItem: {
        width: SCREEN_WIDTH,
        //paddingHorizontal: 24,
        //paddingBottom: 24,
        flex: 1,
        height: '100%',
      },
      carouselInner: {
        flex: 1,
        height: '100%',
        gap: 12,
      },
      cardTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#17202A',
      },
      carouselHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        marginBottom: 12,
        gap: 12,
      },
      poolControls: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        marginHorizontal: 8,
        marginBottom: 14,
        position: 'relative',
        borderWidth: 1,
        borderColor: '#D8E1E1',
        borderRadius: 12,
        backgroundColor: '#FFFFFF',
        shadowColor: '#000000',
        shadowOpacity: 0.06,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 6 },
        elevation: 4,
      },
      rightControls: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
      },
      mobileConfigPanel: {
        marginHorizontal: 8,
        marginBottom: 12,
      },
      mobilePoolFrame: {
        flex: 1,
        minHeight: 0,
        marginHorizontal: 0,
        paddingBottom: 0,
      },
      inlineConfigPanel: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        gap: 12,
      },
      inlineConfigPanelCompact: {
        justifyContent: 'center',
      },
      inlineStepper: {
        gap: 6,
      },
      inlineConfigLabel: {
        fontSize: 12,
        fontWeight: '800',
        color: '#5F6B7A',
        textTransform: 'uppercase',
      },
      inlineStepperShell: {
        minHeight: 36,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#D8E1E1',
        borderRadius: 8,
        backgroundColor: '#FFFFFF',
        overflow: 'hidden',
      },
      inlineNativeStepper: {
        minHeight: 36,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
      },
      inlineStepperButton: {
        width: 36,
        height: 36,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#F3F6F6',
      },
      inlineStepperButtonDisabled: {
        backgroundColor: '#EEF3F2',
        opacity: 0.55,
      },
      inlineStepperButtonText: {
        color: '#17202A',
        fontSize: 17,
        fontWeight: '900',
      },
      inlineStepperValue: {
        minWidth: 36,
        color: '#17202A',
        fontSize: 15,
        fontWeight: '900',
        textAlign: 'center',
      },
      inlineToggle: {
        minHeight: 36,
        alignSelf: 'flex-end',
        justifyContent: 'center',
        paddingHorizontal: 14,
        borderWidth: 1,
        borderColor: '#D8E1E1',
        borderRadius: 8,
        backgroundColor: '#FFFFFF',
      },
      inlineToggleActive: {
        borderColor: '#0A70B5',
        backgroundColor: '#E7F2FA',
      },
      inlineToggleDisabled: {
        opacity: 0.55,
      },
      inlineToggleText: {
        color: '#17202A',
        fontSize: 13,
        fontWeight: '900',
      },
      inlineToggleTextActive: {
        color: '#0A70B5',
      },
      inlineSwitchGroup: {
        minHeight: 36,
        alignSelf: 'flex-end',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
      },
      inlineSwitchLabel: {
        color: '#17202A',
        fontSize: 13,
        fontWeight: '900',
      },
      poolDateContainer: {
        position: 'absolute',
        left: 0,
        right: 0,
        alignItems: 'center',
        pointerEvents: 'none',
      },
      poolDate: {
        fontSize: 20,
        fontWeight: '800',
        color: '#17202A',
        textAlign: 'center',
      },
      poolOutcomeStats: {
        marginTop: 2,
        fontSize: 12,
        fontWeight: '800',
        color: '#5F6B7A',
        textAlign: 'center',
      },
      poolOutcomeSummary: {
        marginTop: 3,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
        gap: 8,
      },
      poolOutcomeSummaryText: {
        fontSize: 12,
        fontWeight: '900',
        textAlign: 'center',
      },
      poolOutcomeCounter: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
      },
      poolOutcomeCounterPrefix: {
        fontSize: 11,
        fontWeight: '900',
      },
      poolOutcomePositive: {
        color: '#157F3B',
      },
      poolOutcomeNegative: {
        color: '#D71920',
      },
      poolOutcomePending: {
        color: '#A96A00',
      },
      poolOutcomeElige8: {
        color: '#0A70B5',
      },
      poolSuccessesGloveLarge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 999,
        backgroundColor: '#157F3B',
        shadowColor: '#000000',
        shadowOpacity: 0.22,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 6 },
        elevation: 10,
      },
      poolSuccessesGloveTextLarge: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '800',
        marginLeft: 6,
      },
      settingsButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#D8E1E1',
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
      },
      poolSuccessesIcon: {
        marginTop: Platform.OS === 'ios' ? 1 : 0,
      },
      doublesControl: {
        width: 110,
        flexShrink: 0,
        flexDirection: 'column',
        alignItems: 'flex-start',
        gap: 4,
      },
      doublesLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#17202A',
        marginBottom: 4,
        textTransform: 'uppercase',
        letterSpacing: 0.8,
      },
      doublesStepper: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#B9C7C6',
        backgroundColor: '#FFFFFF',
        overflow: 'hidden',
      },
      doublesStepperDisabled: {
        borderColor: '#D8E1E1',
        backgroundColor: '#f3f6fc',
      },
      doublesStepperButton: {
        paddingHorizontal: 12,
        paddingVertical: 8,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F3F6F6',
      },
      doublesStepperButtonLeft: {
        borderTopLeftRadius: 12,
        borderBottomLeftRadius: 12,
        borderRightWidth: 1,
        borderRightColor: '#D8E1E1',
      },
      doublesStepperButtonRight: {
        borderTopRightRadius: 12,
        borderBottomRightRadius: 12,
        borderLeftWidth: 1,
        borderLeftColor: '#D8E1E1',
      },
      doublesStepperButtonDisabled: {
        backgroundColor: '#EEF3F2',
      },
      doublesStepperButtonLabel: {
        fontSize: 18,
        fontWeight: '700',
        color: '#25313F',
      },
      doublesStepperButtonLabelDisabled: {
        color: '#a3adcb',
      },
      doublesValueContainer: {
        minWidth: 48,
        paddingHorizontal: 12,
        paddingVertical: 8,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
      },
      doublesValue: {
        fontSize: 16,
        fontWeight: '600',
        color: '#25313F',
      },
      doublesValueDisabled: {
        color: '#8792A2',
      },
      nativeStepper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Platform.OS === 'ios' ? '#f2f2f7' : '#f5f5f5',
        borderRadius: Platform.OS === 'ios' ? 8 : 4,
        borderWidth: Platform.OS === 'ios' ? 0.5 : 1,
        borderColor: Platform.OS === 'ios' ? '#c7c7cc' : '#d0d0d0',
        overflow: 'hidden',
        height: Platform.OS === 'ios' ? 32 : 36,
        marginTop: 4,
        ...(Platform.OS === 'android' && {
          elevation: 1,
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: 0.1,
          shadowRadius: 1,
        }),
      },
      nativeStepperButton: {
        width: Platform.OS === 'ios' ? 32 : 36,
        height: Platform.OS === 'ios' ? 32 : 36,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRightWidth: Platform.OS === 'ios' ? 0.5 : 1,
        borderRightColor: Platform.OS === 'ios' ? '#c7c7cc' : '#d0d0d0',
      },
      nativeStepperButtonLeft: {
        borderTopLeftRadius: Platform.OS === 'ios' ? 8 : 4,
        borderBottomLeftRadius: Platform.OS === 'ios' ? 8 : 4,
      },
      nativeStepperButtonRight: {
        borderTopRightRadius: Platform.OS === 'ios' ? 8 : 4,
        borderBottomRightRadius: Platform.OS === 'ios' ? 8 : 4,
        borderRightWidth: 0,
      },
      nativeStepperButtonDisabled: {
        backgroundColor: Platform.OS === 'ios' ? '#f2f2f7' : '#f0f0f0',
      },
      nativeStepperButtonLabel: {
        fontSize: Platform.OS === 'ios' ? 18 : 16,
        fontWeight: Platform.OS === 'ios' ? '400' : '500',
        color: Platform.OS === 'ios' ? '#D71920' : '#D71920',
        lineHeight: Platform.OS === 'ios' ? 20 : 18,
      },
      nativeStepperValueContainer: {
        minWidth: Platform.OS === 'ios' ? 40 : 44,
        height: Platform.OS === 'ios' ? 32 : 36,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRightWidth: Platform.OS === 'ios' ? 0.5 : 1,
        borderRightColor: Platform.OS === 'ios' ? '#c7c7cc' : '#d0d0d0',
      },
      nativeStepperValue: {
        fontSize: Platform.OS === 'ios' ? 16 : 14,
        fontWeight: Platform.OS === 'ios' ? '500' : '600',
        color: '#000000',
        textAlign: 'center',
      },
      toggleControl: {
        flexDirection: 'column',
        alignItems: 'flex-end',
        gap: 4,
      },
      toggleLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#17202A',
        marginBottom: 4,
        textTransform: 'uppercase',
        letterSpacing: 0.8,
      },
      toggleLabelDisabled: {
        color: '#8792A2',
      },
      toggleSwitch: {
        ...Platform.select({
          web: {},
          default: { transform: [{ scaleX: 0.8 }, { scaleY: 0.8 }] },
        }),
      },
      carouselHint: {
        flex: 1,
        fontSize: 14,
        color: '#556081',
      },
      carouselButtons: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
      },
      carouselButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#B9C7C6',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
      },
      carouselButtonWide: {
        minWidth: 112,
        paddingHorizontal: 16,
        height: 40,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#B9C7C6',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
      },
      carouselButtonDisabled: {
        backgroundColor: '#EEF3F2',
        borderColor: '#d7dfef',
      },
      carouselButtonLabel: {
        fontSize: 18,
        fontWeight: '700',
        color: '#17202A',
      },
      carouselButtonWideLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#17202A',
      },
      carouselButtonLabelDisabled: {
        color: '#A7B1BE',
      },
      paginationDots: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
        marginTop: 6,
        marginBottom: 4,
      },
      paginationOverlay: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 8,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
        pointerEvents: 'box-none',
      },
      paginationDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#F4A8AC',
      },
      paginationDotActive: {
        width: 20,
        height: 8,
        borderRadius: 6,
        backgroundColor: '#D71920',
      },
      floatingActionButton: {
        position: 'absolute',
        right: 24,
        bottom: 32,
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: '#D71920',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOpacity: 0.18,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 6 },
        elevation: 8,
        zIndex: 20,
      },
      creationModalScreenContainer: {
        flex: 1,
        backgroundColor: '#F7F7F5',
      },
      creationModalScreenContent: {
        flex: 1,
        backgroundColor: '#F7F7F5',
      },
      creationModalScroll: {
        flex: 1,
        backgroundColor: '#F7F7F5',
      },
      creationModalScrollContent: {
        paddingHorizontal: 18,
        paddingTop: 18,
        paddingBottom: 20,
        gap: 14,
      },
      nativeHeaderAction: {
        fontSize: 16,
        fontWeight: '600',
        color: '#17202A',
      },
      nativeHeaderActionPrimary: {
        fontWeight: '800',
        color: '#D71920',
      },
      nativeHeaderActionDisabled: {
        opacity: 0.45,
      },
      creationModalSection: {
        gap: 8,
      },
      creationModalRow: {
        flexDirection: 'row',
        alignItems: 'stretch',
        justifyContent: 'space-between',
        gap: 12,
        flexWrap: 'wrap',
      },
      creationModalLabelRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
      },
      creationModalLabel: {
        fontSize: 12,
        lineHeight: 16,
        fontWeight: '800',
        color: '#5F6B7A',
        textTransform: 'uppercase',
      },
      creationModalElige8Badge: {
        minWidth: 24,
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 12,
        backgroundColor: '#0A70B5',
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '700',
        textAlign: 'center',
      },
      creationModalInput: {
        minHeight: 44,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#D8E1E1',
        backgroundColor: '#FFFFFF',
        fontSize: 15,
        lineHeight: 20,
        color: '#17202A',
      },
      creationModalNameInput: {
        minHeight: 44,
      },
      creationModalDateColumn: {
        flex: 1,
        minWidth: 200,
        gap: 8,
      },
      creationModalDateNative: {
        gap: 12,
        alignItems: 'stretch',
      },
      creationModalNativeStepper: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
      },
      creationModalStepperShell: {
        alignSelf: 'flex-start',
      },
      creationModalDualRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
        gap: 12,
        width: '100%',
      },
      creationModalStepperGroup: {
        flexBasis: '30%',
        flexGrow: 1,
        minWidth: 120,
        gap: 8,
        padding: 12,
        borderWidth: 1,
        borderColor: '#D8E1E1',
        borderRadius: 8,
        backgroundColor: '#FFFFFF',
      },
      creationModalStepperGroupLeft: {
        alignItems: 'flex-start',
      },
      creationModalStepperGroupCenter: {
        alignItems: 'flex-start',
      },
      creationModalElige8Group: {
        flexBasis: '30%',
        flexGrow: 1,
        minWidth: 120,
        gap: 8,
        alignItems: 'flex-start',
        padding: 12,
        borderWidth: 1,
        borderColor: '#D8E1E1',
        borderRadius: 8,
        backgroundColor: '#FFFFFF',
      },
      creationModalStepperValue: {
        fontSize: 18,
        fontWeight: '600',
        color: '#17202A',
      },
      creationModalSwitchGroup: {
        alignItems: 'flex-start',
        gap: 8,
        minWidth: 140,
        padding: 12,
        borderWidth: 1,
        borderColor: '#D8E1E1',
        borderRadius: 8,
        backgroundColor: '#FFFFFF',
      },
      creationModalSwitchColumn: {
        alignItems: 'flex-start',
        gap: 8,
      },
      creationModalSwitchRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
      },
      creationModalSwitchLabel: {
        fontSize: 16,
        fontWeight: '500',
        color: '#17202A',
      },
      creationModalDateWeb: {
        width: '100%',
      },
      creationModalDateField: {
        position: 'relative',
        width: '100%',
        minHeight: 44,
        borderWidth: 1,
        borderColor: '#D8E1E1',
        borderRadius: 8,
        backgroundColor: '#FFFFFF',
        overflow: 'hidden',
      },
      creationModalDateDisplay: {
        position: 'absolute',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        paddingHorizontal: 12,
        paddingVertical: 10,
        flexDirection: 'row',
        alignItems: 'center',
        pointerEvents: 'none',
        zIndex: 0,
      },
      creationModalDateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#D8E1E1',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        backgroundColor: '#FFFFFF',
        alignSelf: 'stretch',
        minHeight: 44,
      },
      creationModalDateButtonText: {
        fontSize: 15,
        fontWeight: '700',
        color: '#17202A',
      },
      creationModalDateFallback: {
        minHeight: 44,
        borderWidth: 1,
        borderColor: '#D8E1E1',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        backgroundColor: '#FFFFFF',
        gap: 4,
        alignItems: 'flex-start',
      },
      creationModalDateFallbackHint: {
        fontSize: 12,
        color: '#8792A2',
      },
      matchesSection: {
        marginTop: 4,
        gap: 10,
      },
      matchRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        width: '100%',
      },
      matchEntry: {
        padding: 10,
        borderWidth: 1,
        borderColor: '#D8E1E1',
        borderRadius: 8,
        backgroundColor: '#FFFFFF',
        gap: 8,
      },
      matchOrderBadge: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#F3F6F6',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#D8E1E1',
      },
      matchOrderText: {
        fontSize: 13,
        fontWeight: '800',
        color: '#5F6B7A',
      },
      matchTeamInput: {
        flexGrow: 1,
        flexShrink: 1,
        flexBasis: 0,
        minHeight: 38,
        borderWidth: 1,
        borderColor: '#D8E1E1',
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 8,
        backgroundColor: '#F8FAFA',
        fontSize: 14,
        color: '#17202A',
      },
      matchSeparator: {
        fontSize: 14,
        fontWeight: '800',
        color: '#8792A2',
        marginHorizontal: 0,
      },
      userSelectorContainer: {
        position: 'relative',
        width: '100%',
        marginTop: 0,
        zIndex: 10000,
      },
      loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 24,
        gap: 12,
      },
      loadingText: {
        fontSize: 16,
        color: '#5F6B7A',
      },
      errorText: {
        fontSize: 14,
        color: '#B42318',
        textAlign: 'center',
        marginTop: 16,
      },
      webScroll: {
        flex: 1,
        backgroundColor: '#F6F7F4',
      },
      webScrollContent: {
        flexGrow: 1,
      },
      webWorkspace: {
        flexGrow: 1,
        paddingHorizontal: 32,
        paddingTop: 32,
        paddingBottom: 48,
        gap: 22,
        backgroundColor: '#F6F7F4',
      },
      webLoadingPanel: {
        minHeight: 480,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
      },
      webWorkspaceHero: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        gap: 24,
      },
      webWorkspaceHeroCopy: {
        maxWidth: 720,
        gap: 8,
      },
      webEyebrow: {
        alignSelf: 'flex-start',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 999,
        backgroundColor: '#FCE7E8',
        color: '#A81218',
        fontSize: 12,
        fontWeight: '800',
        textTransform: 'uppercase',
        letterSpacing: 0.7,
      },
      webWorkspaceTitle: {
        fontSize: 34,
        lineHeight: 40,
        fontWeight: '800',
        color: '#17202A',
      },
      webWorkspaceSubtitle: {
        fontSize: 16,
        lineHeight: 23,
        color: '#5F6B7A',
      },
      webHeroActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        flexWrap: 'wrap',
        justifyContent: 'flex-end',
      },
      webPrimaryButton: {
        minHeight: 42,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 8,
        backgroundColor: '#D71920',
      },
      webPrimaryButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '800',
      },
      webSecondaryButton: {
        minHeight: 42,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#D8E1E1',
        backgroundColor: '#FFFFFF',
      },
      webSecondaryButtonText: {
        color: '#17202A',
        fontSize: 14,
        fontWeight: '700',
      },
      webMetricsRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
      },
      webMetricCard: {
        flexGrow: 1,
        flexBasis: 180,
        minHeight: 88,
        borderWidth: 1,
        borderColor: '#D8E1E1',
        borderRadius: 8,
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 16,
        paddingVertical: 14,
        justifyContent: 'space-between',
        shadowColor: '#000000',
        shadowOpacity: 0.05,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 6 },
        elevation: 3,
      },
      webMetricLabel: {
        fontSize: 12,
        fontWeight: '800',
        color: '#5F6B7A',
        textTransform: 'uppercase',
        letterSpacing: 0.7,
      },
      webMetricValue: {
        fontSize: 28,
        fontWeight: '800',
        color: '#17202A',
      },
      webMainPanel: {
        borderWidth: 1,
        borderColor: '#D8E1E1',
        borderRadius: 8,
        backgroundColor: '#FFFFFF',
        padding: 16,
        gap: 14,
      },
      webPanelHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
      },
      webPoolHeaderMain: {
        gap: 3,
      },
      webPanelTitle: {
        fontSize: 18,
        fontWeight: '800',
        color: '#17202A',
      },
      webPoolSelector: {
        position: 'relative',
        zIndex: 50,
        maxWidth: 420,
      },
      webPoolSelectorButton: {
        minHeight: 52,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderWidth: 1,
        borderColor: '#D8E1E1',
        borderRadius: 8,
        backgroundColor: '#FFFFFF',
      },
      webPoolSelectorCopy: {
        flex: 1,
        minWidth: 0,
      },
      webPoolSelectorLabel: {
        color: '#5F6B7A',
        fontSize: 11,
        fontWeight: '900',
        textTransform: 'uppercase',
      },
      webPoolSelectorValue: {
        marginTop: 2,
        color: '#17202A',
        fontSize: 15,
        fontWeight: '800',
      },
      webPoolSelectorMenu: {
        position: 'absolute',
        top: 60,
        left: 0,
        right: 0,
        maxHeight: 320,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#D8E1E1',
        borderRadius: 8,
        backgroundColor: '#FFFFFF',
        shadowColor: '#000000',
        shadowOpacity: 0.12,
        shadowRadius: 14,
        shadowOffset: { width: 0, height: 8 },
        elevation: 24,
        zIndex: 100,
      },
      webPoolSelectorItem: {
        minHeight: 56,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#EEF3F2',
      },
      webPoolSelectorItemActive: {
        backgroundColor: '#FFF3F3',
      },
      webPoolSelectorItemMain: {
        flex: 1,
        minWidth: 0,
      },
      webPoolSelectorItemDate: {
        fontSize: 14,
        fontWeight: '800',
        color: '#17202A',
      },
      webPoolSelectorItemDateActive: {
        color: '#A81218',
      },
      webPoolSelectorItemMeta: {
        fontSize: 12,
        color: '#8792A2',
        marginTop: 2,
      },
      webPoolSelectorScore: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 999,
        backgroundColor: '#E7F6EC',
      },
      webPoolSelectorScoreText: {
        fontSize: 12,
        fontWeight: '800',
        color: '#157F3B',
      },
      webStatusPill: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        gap: 5,
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 999,
        borderWidth: 1,
      },
      webStatusPillActive: {
        backgroundColor: '#E7F6EC',
        borderColor: '#157F3B',
      },
      webStatusPillProgrammed: {
        backgroundColor: '#FFF4D6',
        borderColor: '#F2C94C',
      },
      webStatusPillClosed: {
        backgroundColor: '#374151',
        borderColor: '#1F2937',
      },
      webStatusPillCompact: {
        marginTop: 4,
        paddingHorizontal: 7,
        paddingVertical: 3,
      },
      webStatusPillText: {
        fontSize: 12,
        fontWeight: '800',
        textTransform: 'uppercase',
      },
      webStatusPillTextActive: {
        color: '#157F3B',
      },
      webStatusPillTextProgrammed: {
        color: '#A96A00',
      },
      webStatusPillTextClosed: {
        color: '#FFFFFF',
      },
      webPoolCardFrame: {
        minHeight: 620,
      },
      webInlineConfigBar: {
        padding: 12,
        borderWidth: 1,
        borderColor: '#D8E1E1',
        borderRadius: 8,
        backgroundColor: '#F8FAFA',
      },
      webPoolOutcomeStats: {
        marginTop: 0,
        justifyContent: 'flex-start',
      },
      webEmptyState: {
        minHeight: 420,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
        borderWidth: 1,
        borderStyle: 'dashed',
        borderColor: '#D8E1E1',
        borderRadius: 8,
        backgroundColor: '#FFF3F3',
      },
      webEmptyStateTitle: {
        color: '#17202A',
        fontSize: 16,
        fontWeight: '700',
      },
      webWorkflowStep: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 10,
        paddingVertical: 5,
      },
      webWorkflowDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginTop: 6,
        backgroundColor: '#D71920',
      },
      webWorkflowText: {
        flex: 1,
        fontSize: 14,
        lineHeight: 20,
        color: '#5F6B7A',
      },
    },
    isDark,
  );

export { createStyles };
export default createStyles(false);
