import { Dimensions, Platform, StyleSheet } from 'react-native';

const SCREEN_WIDTH = Dimensions.get('window').width;

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f4f6fb',
    position: 'relative',
  },
  mobileMenuWrapper: {
    position: 'absolute',
    top: 16,
    right: 16,
    zIndex: 40,
  },
  container: {
    flex: 1,
    height: '100%',
  },
  authContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    gap: 24,
  },
  authTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#1a1f36',
    textAlign: 'center',
  },
  authSubtitle: {
    fontSize: 16,
    color: '#626e91',
    textAlign: 'center',
    lineHeight: 22,
  },
  authButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 28,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#dbe2f2',
    shadowColor: '#000000',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  authButtonIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f4f6fb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  authButtonIconLabel: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ffffff',
  },
  authButtonDisabled: {
    opacity: 0.7,
  },
  authButtonLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a1f36',
  },
  sessionHeader: {
    paddingHorizontal: 24,
    paddingTop: 12,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sessionTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1a1f36',
  },
  menuButtonWrapper: {
    borderRadius: 20,
    overflow: 'hidden',
  },
  menuButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sessionAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#d9e2ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sessionAvatarImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  sessionAvatarText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1a1f36',
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: '#1a1f36',
    textAlign: 'center',
    marginBottom: 16,
  },
  carousel: {
    flex: 1,
    height: '100%',
  },
  carouselContent: {
    alignItems: 'stretch',
    height: '100%',
  },
  carouselItem: {
    width: SCREEN_WIDTH,
    //paddingHorizontal: 24,
    //paddingBottom: 24,
    flex: 1,
    height: '100%',
  },
  carouselInner: {
    flex: 1,
    height: '100%',
    gap: 12,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#24304e',
  },
  carouselHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    marginBottom: 12,
    gap: 12,
  },
  poolControls: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    marginBottom: 16,
    position: 'relative',
  },
  rightControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  poolDateContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
    pointerEvents: 'none',
  },
  poolDate: {
    fontSize: 28,
    fontWeight: '600',
    color: '#4A1A7A',
    textAlign: 'center',
  },
  poolSuccessesGloveLarge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#178E3D',
    shadowColor: '#000000',
    shadowOpacity: 0.22,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 10,
  },
  poolSuccessesGloveTextLarge: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '800',
    marginLeft: 6,
  },
  poolSuccessesIcon: {
    marginTop: Platform.OS === 'ios' ? 1 : 0,
  },
  doublesControl: {
    width: 110,
    flexShrink: 0,
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 4,
  },
  doublesLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#24304e',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  doublesStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#c7d0e6',
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  doublesStepperDisabled: {
    borderColor: '#d7deeb',
    backgroundColor: '#f3f6fc',
  },
  doublesStepperButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#e7edfb',
  },
  doublesStepperButtonLeft: {
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
    borderRightWidth: 1,
    borderRightColor: '#d7deeb',
  },
  doublesStepperButtonRight: {
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    borderLeftWidth: 1,
    borderLeftColor: '#d7deeb',
  },
  doublesStepperButtonDisabled: {
    backgroundColor: '#edf1f9',
  },
  doublesStepperButtonLabel: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2d3a52',
  },
  doublesStepperButtonLabelDisabled: {
    color: '#a3adcb',
  },
  doublesValueContainer: {
    minWidth: 48,
    paddingHorizontal: 12,
    paddingVertical: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
  },
  doublesValue: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2d3a52',
  },
  doublesValueDisabled: {
    color: '#7a86aa',
  },
  nativeStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Platform.OS === 'ios' ? '#f2f2f7' : '#f5f5f5',
    borderRadius: Platform.OS === 'ios' ? 8 : 4,
    borderWidth: Platform.OS === 'ios' ? 0.5 : 1,
    borderColor: Platform.OS === 'ios' ? '#c7c7cc' : '#d0d0d0',
    overflow: 'hidden',
    height: Platform.OS === 'ios' ? 32 : 36,
    marginTop: 4,
    ...(Platform.OS === 'android' && {
      elevation: 1,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 1,
    }),
  },
  nativeStepperButton: {
    width: Platform.OS === 'ios' ? 32 : 36,
    height: Platform.OS === 'ios' ? 32 : 36,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRightWidth: Platform.OS === 'ios' ? 0.5 : 1,
    borderRightColor: Platform.OS === 'ios' ? '#c7c7cc' : '#d0d0d0',
  },
  nativeStepperButtonLeft: {
    borderTopLeftRadius: Platform.OS === 'ios' ? 8 : 4,
    borderBottomLeftRadius: Platform.OS === 'ios' ? 8 : 4,
  },
  nativeStepperButtonRight: {
    borderTopRightRadius: Platform.OS === 'ios' ? 8 : 4,
    borderBottomRightRadius: Platform.OS === 'ios' ? 8 : 4,
    borderRightWidth: 0,
  },
  nativeStepperButtonDisabled: {
    backgroundColor: Platform.OS === 'ios' ? '#f2f2f7' : '#f0f0f0',
  },
  nativeStepperButtonLabel: {
    fontSize: Platform.OS === 'ios' ? 18 : 16,
    fontWeight: Platform.OS === 'ios' ? '400' : '500',
    color: Platform.OS === 'ios' ? '#007aff' : '#1976d2',
    lineHeight: Platform.OS === 'ios' ? 20 : 18,
  },
  nativeStepperValueContainer: {
    minWidth: Platform.OS === 'ios' ? 40 : 44,
    height: Platform.OS === 'ios' ? 32 : 36,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRightWidth: Platform.OS === 'ios' ? 0.5 : 1,
    borderRightColor: Platform.OS === 'ios' ? '#c7c7cc' : '#d0d0d0',
  },
  nativeStepperValue: {
    fontSize: Platform.OS === 'ios' ? 16 : 14,
    fontWeight: Platform.OS === 'ios' ? '500' : '600',
    color: '#000000',
    textAlign: 'center',
  },
  toggleControl: {
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: 4,
  },
  toggleLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#24304e',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  toggleLabelDisabled: {
    color: '#7a86aa',
  },
  toggleSwitch: {
    ...Platform.select({
      web: {},
      default: { transform: [{ scaleX: 0.8 }, { scaleY: 0.8 }] },
    }),
  },
  carouselHint: {
    flex: 1,
    fontSize: 14,
    color: '#556081',
  },
  carouselButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  carouselButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#c7d0e6',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
  },
  carouselButtonWide: {
    minWidth: 112,
    paddingHorizontal: 16,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#c7d0e6',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
  },
  carouselButtonDisabled: {
    backgroundColor: '#eef2fb',
    borderColor: '#d7dfef',
  },
  carouselButtonLabel: {
    fontSize: 18,
    fontWeight: '700',
    color: '#24304e',
  },
  carouselButtonWideLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#24304e',
  },
  carouselButtonLabelDisabled: {
    color: '#97a3c5',
  },
  paginationDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginTop: 6,
    marginBottom: 4,
  },
  paginationOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 8,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    pointerEvents: 'box-none',
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#8B7BC7',
  },
  paginationDotActive: {
    width: 20,
    height: 8,
    borderRadius: 6,
    backgroundColor: '#4A1A7A',
  },
  floatingActionButton: {
    position: 'absolute',
    right: 24,
    bottom: 32,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#4A1A7A',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
    zIndex: 20,
  },
  creationModalOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(18, 22, 35, 0.35)',
  },
  creationModalContainer: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 32,
  },
  creationModalContent: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 20,
    maxHeight: '85%',
    width: '100%',
    maxWidth: 440,
    alignSelf: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 16,
    gap: 16,
  },
  creationModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  creationModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1a1f36',
  },
  creationModalScroll: {
    flex: 1,
  },
  creationModalScrollContent: {
    paddingBottom: 16,
    gap: 18,
  },
  creationModalSection: {
    gap: 12,
  },
  creationModalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    flexWrap: 'wrap',
  },
  creationModalLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  creationModalLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#24304e',
  },
  creationModalElige8Badge: {
    minWidth: 24,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 12,
    backgroundColor: '#2d6cdf',
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  creationModalInput: {
    minHeight: 100,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d7deeb',
    backgroundColor: '#ffffff',
    fontSize: 16,
    lineHeight: 22,
    color: '#1a1f36',
  },
  creationModalDateColumn: {
    flex: 1,
    minWidth: 200,
    gap: 12,
  },
  creationModalDateNative: {
    gap: 12,
    alignItems: 'flex-start',
  },
  creationModalNativeStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  creationModalStepperShell: {
    alignSelf: 'flex-start',
  },
  creationModalDualRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    gap: 12,
    width: '100%',
  },
  creationModalStepperGroup: {
    flexBasis: '30%',
    flexGrow: 1,
    minWidth: 120,
    gap: 10,
  },
  creationModalStepperGroupLeft: {
    alignItems: 'flex-start',
  },
  creationModalStepperGroupCenter: {
    alignItems: 'flex-start',
  },
  creationModalElige8Group: {
    flexBasis: '30%',
    flexGrow: 1,
    minWidth: 120,
    gap: 10,
    alignItems: 'flex-end',
  },
  creationModalStepperValue: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1a1f36',
  },
  creationModalSwitchGroup: {
    alignItems: 'flex-end',
    gap: 6,
    minWidth: 140,
  },
  creationModalSwitchColumn: {
    alignItems: 'flex-start',
    gap: 8,
  },
  creationModalSwitchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  creationModalSwitchLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: '#1a1f36',
  },
  creationModalDateWeb: {
    width: '100%',
  },
  creationModalDateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d7deeb',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#ffffff',
    alignSelf: 'flex-start',
  },
  creationModalDateButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a1f36',
  },
  creationModalDateFallback: {
    gap: 6,
    alignItems: 'flex-start',
  },
  creationModalDateFallbackHint: {
    fontSize: 12,
    color: '#6f7a9b',
  },
  creationModalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  creationModalActionsCompact: {
    justifyContent: 'flex-end',
  },
  creationModalActionsSingle: {
    justifyContent: 'flex-start',
  },
  creationModalActionButton: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 14,
  },
  creationModalActionGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  creationModalCancelButton: {
    borderWidth: 1,
    borderColor: '#d7deeb',
    backgroundColor: '#ffffff',
  },
  creationModalSubmitButton: {
    backgroundColor: '#4A1A7A',
  },
  creationModalFinalizeButton: {
    backgroundColor: '#f28b2b',
  },
  creationModalFinalizeButtonLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
  },
  creationModalCancelLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a1f36',
  },
  creationModalSubmitLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
  },
  creationModalActionButtonDisabled: {
    opacity: 0.6,
  },
  matchesSection: {
    marginTop: 24,
    gap: 12,
  },
  matchesHeader: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a1f36',
  },
  matchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    width: '100%',
  },
  matchOrderBadge: {
    width: 18,
    height: 18,
    borderRadius: 12,
    backgroundColor: '#f0f3ff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  matchOrderText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#4A1A7A',
  },
  matchTeamInput: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: '100%',
    minHeight: 20,
    borderWidth: 1,
    borderColor: '#d7deeb',
    borderRadius: 12,
    paddingHorizontal: 4,
    paddingVertical: 3,
    backgroundColor: '#ffffff',
    fontSize: 15,
    color: '#1a1f36',
    width: '100%',
  },
  matchSeparator: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4A1A7A',
    marginHorizontal: 0,
  },
  matchDivider: {
    height: 1,
    backgroundColor: '#e1e6f3',
    marginVertical: 5,
    marginHorizontal: 12,
  },
  matchUserSelector: {
    minWidth: 120,
    alignItems: 'flex-start',
  },
  matchUserCapsule: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
  },
  matchUserCapsuleText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#000000',
  },
  matchUserPlaceholder: {
    fontSize: 13,
    fontWeight: '500',
    color: '#6f7a9b',
  },
  finalizeModalContainer: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  finalizeModalCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingHorizontal: 24,
    paddingVertical: 24,
    gap: 16,
    shadowColor: '#000000',
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 12,
  },
  finalizeModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a1f36',
  },
  finalizeModalSubtitle: {
    fontSize: 14,
    color: '#4a5578',
  },
  finalizeModalInput: {
    borderWidth: 1,
    borderColor: '#d7deeb',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 16,
    color: '#1a1f36',
    backgroundColor: '#ffffff',
  },
  finalizeModalError: {
    fontSize: 13,
    color: '#b3261e',
  },
  finalizeModalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  },
  finalizeModalButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
  },
  finalizeModalCancelButton: {
    borderWidth: 1,
    borderColor: '#d7deeb',
    backgroundColor: '#ffffff',
  },
  finalizeModalSubmitButton: {
    backgroundColor: '#4A1A7A',
  },
  finalizeModalCancelLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1a1f36',
  },
  finalizeModalSubmitLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: '#ffffff',
  },
  finalizeModalButtonDisabled: {
    opacity: 0.6,
  },
  userSelectorContainer: {
    position: 'relative',
    width: '50%',
    marginTop: 8,
    zIndex: 10000,
  },
  userComboBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#d7deeb',
    borderRadius: 12,
    paddingHorizontal: 4,
    paddingVertical: 3,
    backgroundColor: '#ffffff',
    minHeight: 30,
  },
  userComboBoxText: {
    fontSize: 15,
    color: '#1a1f36',
    flex: 1,
  },
  userDropdown: {
    position: 'absolute',
    left: 24,
    width: '50%',
    backgroundColor: '#ffffff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d7deeb',
    shadowColor: '#000000',
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 16,
    zIndex: 10001,
    maxHeight: 200,
    marginTop: 4,
  },
  userDropdownOption: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f3ff',
  },
  userDropdownOptionCapsule: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    alignSelf: 'flex-start',
  },
  dropdownBackdrop: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    zIndex: 10000,
  },
  menuOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(18, 22, 35, 0.25)',
    paddingHorizontal: 16,
    paddingTop: 70,
    zIndex: 50,
    elevation: 10,
  },
  menuContainer: {
    alignSelf: 'flex-end',
    width: 280,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 18,
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 12,
    zIndex: 51,
  },
  menuInner: {
    gap: 12,
  },
  menuProfile: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 4,
  },
  menuName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a1f36',
  },
  menuEmail: {
    fontSize: 13,
    color: '#6f7a9b',
  },
  menuDivider: {
    height: 1,
    backgroundColor: '#e5e9f5',
  },
  menuItem: {
    paddingVertical: 10,
  },
  menuItemLabel: {
    fontSize: 15,
    color: '#1a1f36',
    fontWeight: '500',
  },
  menuItemDanger: {
    color: '#d14c4c',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    gap: 12,
  },
  loadingText: {
    fontSize: 16,
    color: '#536089',
  },
  errorText: {
    fontSize: 14,
    color: '#b3261e',
    textAlign: 'center',
    marginTop: 16,
  },
  webScroll: {
    flex: 1,
  },
  webScrollContent: {
    flexGrow: 1,
  },
});

export default styles;
