version: '3.9'

services:
  db:
    security_opt:
      - no-new-privileges:true
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: kini
      POSTGRES_PASSWORD: kini
      POSTGRES_DB: kini
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
