services:
  kini_api:
    build:
      target: dev
    environment:
      NODE_ENV: development
    command:
      [
        'node',
        '/workspace/scripts/openbao-run.mjs',
        '--',
        'npm',
        'run',
        'start:dev',
      ]
    healthcheck:
      start_period: 90s
    develop:
      watch:
        - action: sync
          path: ../apps/api/src
          target: /workspace/apps/api/src
        - action: sync+restart
          path: ../apps/api/nest-cli.json
          target: /workspace/apps/api/nest-cli.json
        - action: sync+restart
          path: ../apps/api/tsconfig.json
          target: /workspace/apps/api/tsconfig.json
        - action: rebuild
          path: ../package-lock.json
        - action: rebuild
          path: ../apps/api/package.json

  kini_web:
    build:
      target: dev
    environment:
      NODE_ENV: development
    command: ['npm', 'exec', '--', 'next', 'dev', '-H', '0.0.0.0', '-p', '3001']
    healthcheck:
      start_period: 60s
    develop:
      watch:
        - action: sync
          path: ../apps/web/src
          target: /workspace/apps/web/src
        - action: sync
          path: ../apps/web/messages
          target: /workspace/apps/web/messages
        - action: sync
          path: ../apps/web/public
          target: /workspace/apps/web/public
        - action: sync+restart
          path: ../apps/web/next.config.js
          target: /workspace/apps/web/next.config.js
        - action: rebuild
          path: ../package-lock.json
        - action: rebuild
          path: ../apps/web/package.json
