{
 "title": "Trivy Vulnerabilities",
 "templating": {
  "list": [
   {
    "name": "project",
    "query": "label_values({source=\"trivy\"}, project)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total vulns (last 24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"trivy\"} | json [24h]))"
    }
   ]
  },
  {
   "title": "CRITICAL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({source=\"trivy\"} | json | Severity=\"CRITICAL\" [24h]))"
    }
   ]
  },
  {
   "title": "HIGH",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({source=\"trivy\"} | json | Severity=\"HIGH\" [24h]))"
    }
   ]
  },
  {
   "title": "MEDIUM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({source=\"trivy\"} | json | Severity=\"MEDIUM\" [24h]))"
    }
   ]
  },
  {
   "title": "LOW",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({source=\"trivy\"} | json | Severity=\"LOW\" [24h]))"
    }
   ]
  },
  {
   "title": "Vulns by Severity (last 7d)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (Severity) (count_over_time({source=\"trivy\"} | json [7d]))"
    }
   ]
  },
  {
   "title": "Vulns by Project (last 7d)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
   "targets": [
    {
     "expr": "sum by (project) (count_over_time({source=\"trivy\"} | json [7d]))"
    }
   ]
  },
  {
   "title": "All Vulnerabilities (last 7d)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{source=\"trivy\"} | json | line_format \"{{.Severity}} | {{.VulnerabilityID}} | {{.PkgName}}@{{.InstalledVersion}} | {{.project}}\""
    }
   ]
  }
 ]
}